# Generated by Django 5.0.6 on 2024-07-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('Codigo', models.TextField(max_length=16, primary_key=True, serialize=False)),
                ('Nombre', models.TextField(max_length=30)),
                ('Descripcion', models.TextField(max_length=100)),
                ('Cantidad', models.IntegerField()),
                ('Precio', models.FloatField()),
                ('Imagen', models.ImageField(null=True, upload_to='Productos')),
            ],
        ),
    ]
