# Generated by Django 5.0.4 on 2024-07-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('Codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.TextField(max_length=20)),
                ('Email', models.EmailField(max_length=100)),
                ('Telefono', models.TextField(max_length=15)),
                ('Mensaje', models.TextField(max_length=150)),
            ],
        ),
    ]
