# Generated by Django 5.0.4 on 2024-07-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistemas', '0002_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='Mensaje',
            field=models.TextField(max_length=300),
        ),
    ]
