# Generated by Django 5.0.4 on 2024-10-23 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistemas', '0003_alter_contacto_mensaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
