# Generated by Django 5.0.6 on 2024-10-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistemas', '0005_productos_microdescripcion_alter_productos_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='MicroDescripcion',
            field=models.TextField(max_length=200),
        ),
    ]
